server:
  port: 8888
spring:
  application:
    name: config-server
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
#          search-locations: file://${user.home}/development/springboot/git-local-repo # home
#          search-locations: file://${user.home}/Development/springboot/msa-with-spring-cloud-config # dk
          search-locations: file:///E:\Development\springboot\/msa-with-spring-cloud-config # home_win
        git:
#          uri: file:///Users/cyoung90/development/springboot/git-local-repo
          uri: https://github.com/chayoung-choi/msa-with-spring-cloud-config
#          username: [username] #private일 경우
#          password: [password]
management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh
